### ISSUE TITLE
Please publish Cargo.lock with the crate

### ISSUE THREAD

**Issue by polyzen** [hoodie/toastify#3]
```
    Updating crates.io index
    Updating git repository `https://github.com/hoodie/notify-rust/`
error: the lock file needs to be updated but --locked was passed to prevent this
```

**Comment by hoodie** [comment]
sure thing, how about now?

**Comment by polyzen** [comment]
Thank you very much. :)

I see this is now also available as a crate. Could you try this to publish the lock file with the crate?:
https://github.com/rust-lang/cargo/issues/5654

**Comment by hoodie** [comment]
That's not the default? I thought it published all checked in files automatically, I'll look

**Comment by polyzen** [comment]
https://github.com/rust-lang/cargo/blob/0.31.0/src/cargo/sources/path.rs#L346-L349

Edit: Please also tag the `0.3.4` release. :)

**Comment by polyzen** [comment]
I've learned unstable Cargo features require Cargo nightly. Will bump this once it's stabilized.

**Comment by hoodie** [comment]
@polyzen ping

**Comment by polyzen** [comment]
> [Cargo will be changed to always include Cargo.lock in the .crate file if the package has binaries or examples.](https://github.com/rust-lang/cargo/issues/5654#issuecomment-497863987)
